### ISSUE TITLE
UserManager.jar Fails to link to admin cert on fresh install

### ISSUE THREAD

**Issue by anxzik** [TAK-Product-Center/Server#52]
i have tried every which way you can to execute java -jar /opt/tak/utils/UserManager.jar certmod -A /opt/tak/certs/files/admin.pem 

and in return i get: `root@tak:/opt/tak# java -jar /opt/tak/utils/UserManager.jar certmod -A /opt/tak/certs/files/admin.pem
java.lang.reflect.InvocationTargetException
java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
        at com.bbn.marti.takcl.cli.CommandCommon.invokeMethodFromModuleWithParams(CommandCommon.java:85)
        at com.bbn.marti.takcl.cli.advanced.AdvancedParamParser.execute(AdvancedParamParser.java:285)
        at com.bbn.marti.takcl.cli.advanced.AdvancedCliMainHelper.main(AdvancedCliMainHelper.java:131)
        at com.bbn.marti.UserManager.main(UserManager.java:61)
Caused by: java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:569)
        at com.bbn.marti.takcl.cli.CommandCommon.invokeMethodFromModuleWithParams(CommandCommon.java:52)
        ... 3 more
Caused by: class org.apache.ignite.IgniteException: Failed to find deployed service: distributed-user-file-manager
        at org.apache.ignite.internal.processors.service.GridServiceProxy.invokeMethod(GridServiceProxy.java:202)
        at org.apache.ignite.internal.processors.service.GridServiceProxy$ProxyInvocationHandler.invoke(GridServiceProxy.java:511)
        at jdk.proxy2/jdk.proxy2.$Proxy40.getUsers(Unknown Source)
        at com.bbn.marti.takcl.AppModules.OnlineFileAuthModule.innerUserCertMod(OnlineFileAuthModule.java:137)
        at com.bbn.marti.takcl.AppModules.OnlineFileAuthModule.certmod(OnlineFileAuthModule.java:213)
        ... 8 more
java.lang.reflect.InvocationTargetException
root@tak:/opt/tak# 
`

I have spun up multiple instances  looked at multiple guides and the comand is the same in all. I am not sure if i am executing this correctly or theres an issue with java in 5.2.

It is a ubuntu GCP instance. side note i originally had postgres iissues aswell, with versioning and possibly that has something to do with it? i have since been able to connect db and look at it on pgadmin4 and it appears to be populated properly

**Comment by starkindustries** [comment]
Also having the same issue:
```
$ sudo java -jar /opt/tak/utils/UserManager.jar certmod -A /opt/tak/certs/files/admin.pem
java.lang.reflect.InvocationTargetException
java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
	at com.bbn.marti.takcl.cli.CommandCommon.invokeMethodFromModuleWithParams(CommandCommon.java:85)
	at com.bbn.marti.takcl.cli.advanced.AdvancedParamParser.execute(AdvancedParamParser.java:285)
	at com.bbn.marti.takcl.cli.advanced.AdvancedCliMainHelper.main(AdvancedCliMainHelper.java:131)
	at com.bbn.marti.UserManager.main(UserManager.java:61)
Caused by: java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:569)
	at com.bbn.marti.takcl.cli.CommandCommon.invokeMethodFromModuleWithParams(CommandCommon.java:52)
	... 3 more
Caused by: class org.apache.ignite.IgniteException: Failed to find deployed service: distributed-user-file-manager
	at org.apache.ignite.internal.processors.service.GridServiceProxy.invokeMethod(GridServiceProxy.java:202)
	at org.apache.ignite.internal.processors.service.GridServiceProxy$ProxyInvocationHandler.invoke(GridServiceProxy.java:511)
	at jdk.proxy2/jdk.proxy2.$Proxy40.getUsers(Unknown Source)
	at com.bbn.marti.takcl.AppModules.OnlineFileAuthModule.innerUserCertMod(OnlineFileAuthModule.java:137)
	at com.bbn.marti.takcl.AppModules.OnlineFileAuthModule.certmod(OnlineFileAuthModule.java:213)
	... 8 more
java.lang.reflect.InvocationTargetException
```

**Comment by tangothr33** [comment]
Hi there! Try the following:
1. Stop the takserver via `systemctl stop takserver`
2. Modify /opt/tak/CoreConfig.xml file's <security> tag information. Make sure it lines up with the filenames you provided when you created the certificates (with makeCert.sh)
3. Restart the takserver and check /opt/tak/logs for ERRORs.
4. Run sudo java -jar /opt/tak/utils/UserManager.jar certmod -A /opt/tak/certs/files/$(yourAdminFile).pem
